services:
  fastapi:
    image: image-fastapi-docker
    build: .
    container_name: container-fastapi-docker
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload